# Generated by Django 3.1.7 on 2021-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('selection1', models.CharField(max_length=100)),
                ('selection2', models.CharField(max_length=100)),
                ('selection3', models.CharField(max_length=100)),
                ('selection4', models.CharField(max_length=100)),
                ('selection5', models.CharField(max_length=100)),
            ],
        ),
    ]
